### ISSUE TITLE
Confluent Kafka Connect requires an empty constructor

### ISSUE THREAD

**Issue by dev-mansonthomas** [SolaceProducts/pubsubplus-connector-kafka-source#41]
Hello There,

I've tried to deploy this sample code into Conlufent Kafka Connect  7.0, 

https://github.com/SolaceProducts/pubsubplus-connector-kafka-source/blob/master/src/main/java/com/solace/connector/kafka/connect/source/msgprocessors/SolSampleSimpleMessageProcessor.java

and I've got the following error : 
```
[2022-01-07 10:56:14,604] ERROR WorkerSourceTask{id=SolaceSourceConnectorConnector_0-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Encountered exception in creating the message processor.
	at com.solace.connector.kafka.connect.source.SolaceSourceTask.start(SolaceSourceTask.java:73)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.initializeAndStart(WorkerSourceTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for com.solace.connector.kafka.connect.source.SolMessageProcessorIF
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:391)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:395)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:430)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:415)
	at com.solace.connector.kafka.connect.source.SolaceSourceTask.start(SolaceSourceTask.java:70)
	... 8 more
Caused by: java.lang.NoSuchMethodException: com.solace.connector.kafka.connect.source.SolMessageProcessorIF.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:389)
	... 12 more
[2022-01-07 10:56:14,607] INFO ================ Shutting down PubSub+ Source Connector (com.solace.connector.kafka.connect.source.SolaceSourceTask)
```

adding

```
    public SourceMessageProcessor(){    
}
```

fix the issue

**Comment by kbreit-insight** [comment]
I am seeing this same error using Strimzi provided Kafka. Has anyone been able to fix or workaround the problem?
