### ISSUE TITLE
Solace connection fails but KafkaConnect status is still RUNNING

### ISSUE THREAD

**Issue by tooptoop4** [SolaceProducts/pubsubplus-connector-kafka-source#47]
i am on latest version, the connector was running ok before and writing messages to kafka but then later on it got this exception. But KafkaConnect status stayed RUNNING, so it is silently crashed. Need KafkaConnect status to change to FAILED so alert can be raised or livenessprobe can autorestart

```
[2022-06-16 19:58:35,127] INFO Client-1: (Client name: kafka-connect-redact/52/00510001/UHWK6gklrN   Local addr: redactip Local port: 47940   Remote addr: redacthost  Remote port: 55443) - handleException(): Channel Closed Event (smfclient 1) (com.solacesystems.jcsmp.protocol.impl.TcpClientChannel)
[2022-06-16 19:58:35,128] INFO Client-1: handleException(): Channel Closed Event (smfclient 1) with exception: Error communicating with the router. (KeepAlive) cur_stack=Thread: "Context_2_ReactorThread" daemon  id=81, prio=5:   com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.handleException(TcpClientChannel.java:1374)   com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.handleKeepaliveException(TcpClientChannel.java:329)      com.solacesystems.jcsmp.protocol.impl.KeepaliveTimeoutHandler.handleTimeout(KeepaliveTimeoutHandler.java:57)         com.solacesystems.jcsmp.impl.timers.impl.JCSMPTimerQueueImpl.runAllTo(JCSMPTimerQueueImpl.java:91)   com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor.eventLoop(SyncEventDispatcherReactor.java:168)     com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor$SEDReactorThread.run(SyncEventDispatcherReactor.java:338)       java.base/java.lang.Thread.run(Thread.java:829)  (com.solacesystems.jcsmp.protocol.impl.TcpClientChannel)
[2022-06-16 19:58:35,128] INFO Client-1: (Client name: kafka-connect-redact/52/00510001/UHWK6gklrN   Local addr: redactip Local port: 47940   Remote addr: redacthost  Remote port: 55443) - startReconnect(): Channel Closed Event (smfclient 1); exception: Error communicating with the router. (KeepAlive) cur_stack=Thread: "Context_2_ReactorThread" daemon  id=81, prio=5:      com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.startReconnect(TcpClientChannel.java:1335)    com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.handleException(TcpClientChannel.java:1399)      com.solacesystems.jcsmp.protocol.impl.TcpClientChannel.handleKeepaliveException(TcpClientChannel.java:329)   com.solacesystems.jcsmp.protocol.impl.KeepaliveTimeoutHandler.handleTimeout(KeepaliveTimeoutHandler.java:57)         com.solacesystems.jcsmp.impl.timers.impl.JCSMPTimerQueueImpl.runAllTo(JCSMPTimerQueueImpl.java:91)  com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor.eventLoop(SyncEventDispatcherReactor.java:168)      com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor$SEDReactorThread.run(SyncEventDispatcherReactor.java:338)       java.base/java.lang.Thread.run(Thread.java:829)  (com.solacesystems.jcsmp.protocol.impl.TcpClientChannel)
[2022-06-16 19:58:35,130] INFO Received Flow (Queue) Event FLOW_DOWN with info Error communicating with the router. (KeepAlive) with exception {}
 (com.solace.connector.kafka.connect.source.SolFlowEventCallBackHandler)
com.solacesystems.jcsmp.JCSMPTransportException: Error communicating with the router. (KeepAlive)
        at com.solacesystems.jcsmp.protocol.impl.KeepaliveTimeoutHandler.handleTimeout(KeepaliveTimeoutHandler.java:56)
        at com.solacesystems.jcsmp.impl.timers.impl.JCSMPTimerQueueImpl.runAllTo(JCSMPTimerQueueImpl.java:91)
        at com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor.eventLoop(SyncEventDispatcherReactor.java:168)
        at com.solacesystems.jcsmp.protocol.nio.impl.SyncEventDispatcherReactor$SEDReactorThread.run(SyncEventDispatcherReactor.java:338)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-06-16 19:58:35,133] INFO Client-1: Stale reconnect task, aborting reconnect. (com.solacesystems.jcsmp.protocol.impl.TcpClientChannel)
[2022-06-16 19:58:35,134] INFO Source of the Flow (Queue) event: com.solacesystems.jcsmp.impl.flow.FlowHandleImpl
 (com.solace.connector.kafka.connect.source.SolFlowEventCallBackHandler)
[2022-06-16 19:58:35,135] INFO Received Session Event DOWN_ERROR with info null
 (com.solace.connector.kafka.connect.source.SolSessionEventCallbackHandler)
[2022-06-16 19:58:35,135] INFO Client-1: Channel Closed (smfclient 1) (com.solacesystems.jcsmp.protocol.impl.TcpClientChannel)
[2022-06-16 19:58:35,135] INFO Client-1: SubChannel (smfclient 1, name=kafka-connect-redact/52/00510001/UHWK6gklrN, desc=) threw exception, non-recoverable.  (com.solacesystems.jcsmp.impl.flow.SubFlowManagerImpl)
com.solacesystems.jcsmp.JCSMPTransportException: (JCSMPTransportException) Error communicating with the router. (KeepAlive)
        at com.solacesystems.jcsmp.protocol.impl.TcpClientChannel$ClientChannelReconnect.call(TcpClientChannel.java:2438)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-06-16 19:58:35,136] INFO JCSMP Exception in SolMessageQueueProcessorCallback (JCSMPTransportException) Error communicating with the router. (KeepAlive)
 (com.solace.connector.kafka.connect.source.SolMessageQueueCallbackHandler)
```
cc @Nephery @bczoma @KenBarr @TKTheTechie @dev-mansonthomas @Chambras @PhilippeKhalife @fhussonnois @unixunion @lakshmanpython  @leadingsoftjp @Shimahosseini @shalinsurface @farmountain

in these places is where i think its just logging the exception without throwing up:
https://github.com/SolaceProducts/pubsubplus-connector-kafka-source/blob/master/src/main/java/com/solace/connector/kafka/connect/source/SolMessageQueueCallbackHandler.java#L52
https://github.com/SolaceProducts/pubsubplus-connector-kafka-source/blob/master/src/main/java/com/solace/connector/kafka/connect/source/SolFlowEventCallBackHandler.java#L33-L34
https://github.com/SolaceProducts/pubsubplus-connector-kafka-source/blob/e0fcb7831e2c595ee86eb6569163f76633b533c7/src/main/java/com/solace/connector/kafka/connect/source/SolMessageTopicCallbackHandler.java#L51

**Comment by bczoma** [comment]
Addressed in v2.3.0, setting task to failed state in case of connection error to PubSub+ broker event destination
